sonar.projectKey=bookingweb
sonar.projectName=bookingWeb
sonar.sources=app,resources,routes,database,config,public/js
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/build/**,storage/**,bootstrap/cache/**
sonar.test.exclusions=vendor/**,node_modules/**
sonar.sourceEncoding=UTF-8
sonar.php.exclusions=vendor/**
